config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :links, only: [:new, :show, :create, :destroy] do
    # Adds route for search action in links controller
    get 'search', on: :collection
  end

  resources :visits do
    # Adds route for empty_logg & index actions in visits controller
    collection do
      get 'empty_logg'
      get 'index'
    end
  end

  # Sets root to new action in links cointroller
  root to: "links#new"
  # Sending incoming urls not matched to existing routes via get to short_redirect method in links controller
  # the entered url is stored in params hash with key :url_short
  match ':url_short', to: 'links#short_redirect', via: [:get]
end

app/models/visit.rb
class Visit < ApplicationRecord
  validates :remote_host, :remote_addr, :http_user_agent, :http_referer, :request_uri, presence: true
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # Restricts access to  logged in admins
  before_action :authenticate_admin!
  # collect all entrys in visits table and store them in @visits which is available in view index.html.erb
  def index
    @visits = Visit.all
  end

  # deletes all entries in visits table
  # redirects to Visit#index
  def empty_logg
    Visit.delete_all
    flash[:success] = 'Logg was successfully deleted!'
    redirect_to visits_path
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/index.html.erb
<div class="card-table">
<h1>Visitors Logg</h1>
<% if @visits.empty? %>
    <h2><b>No visits to show!</b></h2></br>
    <p >That's just sad :(</p></br>
<% else %>

  <table class="table table-bordered table-striped table-hover table-responsive" >
    <thead class="thead-inverse">
      <tr>
        <th>Visit Time</th>
        <th>Remote Host</th>
        <th>Remote address</th>
        <th>User Agent</th>
        <th>HTTP Referer</th>
        <th>Request URI</th>
      </tr>
    </thead>
    <tbody>
      <% @visits.each do |visit| %>
        <tr>
          <td><%= visit.created_at.to_time %></td>
          <td><%= visit.remote_host.titleize %></td>
          <td><%= visit.remote_addr.titleize %></td>
          <td><%= visit.http_user_agent["browser"].titleize %></td>
          <td><%= visit.http_referer.titleize %></td>
          <td><%= visit.request_uri.titleize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>
<p><%= link_to 'Back To Home', root_path %> |
   <%= link_to "Edit Account", edit_admin_registration_path %> |
   <%= link_to "Empty logg",empty_logg_visits_path, method: :get, data: { confirm: 'Are you sure you want to do this?', title: 'Delete logg!' }%></p>
</div>