config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :links, only: [:new, :show, :create, :destroy] do
    # Adds route for search action in links controller
    get 'search', on: :collection
  end

  resources :visits do
    # Adds route for empty_logg & index actions in visits controller
    collection do
      get 'empty_logg'
      get 'index'
    end
  end

  # Sets root to new action in links cointroller
  root to: "links#new"
  # Sending incoming urls not matched to existing routes via get to short_redirect method in links controller
  # the entered url is stored in params hash with key :url_short
  match ':url_short', to: 'links#short_redirect', via: [:get]
end

app/models/link.rb
class Link < ApplicationRecord
  # Using gem https://github.com/ralovets/valid_url to validate correct URL
  # Uses hook to run method before object is saved to db
  validates :url, :url_short, :admin_code, presence: true
  validates :url_short, :admin_code, uniqueness: true
  validates :url, url: true
  before_save :add_protocol

  # overriding to use admin_code instead of id with urls
  def to_param
    admin_code
  end

  protected
  # Checking with regex if protocol is missing at start of url and adds it if missing.
  def add_protocol
    unless self.url[/\Ahttp:\/\//i] || self.url[/\Ahttps:\/\//i]
      self.url = "http://#{self.url}"
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :destroy]

  # renders show view.
  # before_action runs set_link making the right link object available to the view
  def show
  end

  # Sets up a new link object (without saving to database) and makes it available to the view
  def new
    @link = Link.new
  end

  # Sets up a new link object with :url from params hash
  # Sends the object to UniqueAttributesAssigner which returns a new object with correct unique attributes
  # Creates a flash message if theres errors in Link object
  # Redirects to home#index if object is saved successfuly. Renders new if not.
  def create
    @link = Link.new(url: link_params[:url])
    @link = UniqueAttributesAssigner.ensure_unique(@link)

    if  @link.save
      flash[:success] = 'Shorty was successfully created!'
      redirect_to @link
    else
      if @link.errors.any?
        flash[:error] = collect_errors
      end
      redirect_to root_path
    end
  end

  # Uses destroy method in model to remove the databaseentry related to the link object
  # Redirects to home#index
  def destroy
    @link.destroy
    flash[:success] = 'Shorty was successfully deleted!'
    redirect_to root_path
  end

  # uses contents of params hash to find matching link entry in db
  # redirects user original url
  # captures desired data from request.env and sends it RequestLogger as hash
  def short_redirect
    env = {
      remote_host: request.env["REMOTE_HOST"],
      remote_addr: request.env["REMOTE_ADDR"],
      http_user_agent: request.env["HTTP_USER_AGENT"],
      http_referer: request.env["HTTP_REFERER"],
      request_uri: request.env["REQUEST_URI"]
    }
    RequestLogger.logg_request(env)
    @link = Link.find_by(url_short: params[:url_short])
    if @link.nil?
      flash[:error] = 'The Shorty you tried to visit does not exist!'
      redirect_to root_path
    else
      redirect_to @link.url
    end
  end

  # Gets admin_code passed via params from form data.
  # Redirects to root if there is no match
  # redirects to show action for fetched object if theres a match.
  def search
    @link = Link.find_by(admin_code: params[:admin_code])
    if @link.nil?
      flash[:error] = 'No match for supplied code.'
      redirect_to root_path
    else
      redirect_to @link
    end
  end

  private
    # Sets up @link object from params hash via callback before destroy action
    # Sets link by admin code instead of id
    def set_link
      @link = Link.find_by_admin_code(params[:id])
    end

    # creates a string of all errors in Link object
    def collect_errors
      flash_message = ""
      @link.errors.full_messages.each do |message|
        flash_message += message
        flash_message << "\n"
      end
      flash_message
    end

    # Autogenerated code from creating scafold, protects you from forged params hash
    # Removed url_short since its generated internaly
    def link_params
      params.require(:link).permit(:url)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_dialog.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">There is no Admin</h4>
      </div>
      <div class="modal-body">
        <p>There seems to be no registered admin.</p>
        <p>You should go create one!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"><a href="/admins/sign_up"><font color="white">Go to sign up!</font></a></button>
      </div>
    </div>
  </div>
</div>

app/views/links/_form.html.erb
<%= form_for(link, :html => { :class => "form-inline" }) do |f| %>
  <div class="form-group">
    <label for="inputURL">URL:</label>
    <%= f.text_field :url, autofocus: true, placeholder: 'Your url', id: "inputURL", class: 'form-control' %>
  </div>
    <%= f.submit "Create Shorty",:class=>'btn btn-primary' %>

<% end %>

app/views/links/_search_form.html.erb
<%= form_tag({controller: "links", action: "search"}, method: "get", class: "form-inline") do %>
  <div class="form-group">
    <%= label_tag(:search, "Code:") %>
    <%= text_field_tag(:admin_code, nil, {placeholder: "Your Shorty Code", class: 'form-control'}) %>
  </div>
  <%= submit_tag("Fetch Shorty", :class=>'btn btn-primary') %>
<% end %>

app/views/links/new.html.erb
<div class="card">
  <h1>Welcome to Shorty Links!</h1>
  <p class="lead">Create a new link or view/remove an old one</p>
  <p><%= render 'form', link: @link %></p>
  <p><%= render 'search_form' %></p>
  <% if admin_signed_in? %>
    <p><%= link_to "Show Logg", visits_path %> | <%= link_to "Edit Account", edit_admin_registration_path %></p>
  <% end %>
</div>


<!-- Script to activate modal if Admin.all returns an empty array (admins table is empty) -->
<% if Admin.all == [] %>
  <script type="text/javascript">
      $(document).ready(function(){
          $("#myModal").modal('show');
      });
  </script>
  <%= render 'dialog' %>
<% end %>

app/views/links/show.html.erb
<div class="card">
  <h1>Your Shorty!</h1></br>
  <strong><p>Use the shorty instead of your original URL and we'll redirect the visitors.</br></strong>
   Save your admin code if you want to get back to this page.</p></br>
   <p>
     <strong>Url:</strong>
     <%= @link.url %>
   </p>
   <p>
     <strong>Shorty:</strong>
     <%= root_url + @link.url_short %>
   </p>
   <p>
     <strong>Admin code:</strong>
     <%= @link.admin_code %>
   </p>
   <p><%= link_to 'Delete Shorty', @link, method: :delete, data: { confirm: 'Are you sure you want to do this?', title: 'Delete Shorty!' } %> | <%= link_to 'Back To Start', root_path %></p>
  <p><button class="clipboard-btn btn btn-primary" data-clipboard-text= "<%= root_url + @link.url_short %>">Copy Shorty to clipboard</button></p>
  <% if admin_signed_in? %>
    <p><%= link_to "Show Logg", visits_path %></p>
  <% end %>
</div>